config/routes.rb
Myapp::Application.routes.draw do
  resources :source_data
  root 'source_data#chart'
  get 'sessions/destroy'
  get 'nsnlist'=> 'source_data#nsnlist'
  get 'source'=> 'source_data#source'
  get 'edit' => 'source_data#edit'
  get 'viewsource' => 'source_data#viewsource'
  get 'view' => 'source_data#view'
  get 'dictionary_detail' => 'source_data#dictionary_detail'
  post   'login'   => 'sessions#create'
  get 'login' => 'sessions#login'
  get 'logout' => 'sessions#destroy'
  get 'new' => 'users#new'
  get 'factorys/show'
  get 'view_path' => 'factorys#view'
  get 'external_view_path' => 'factorys#external_view'
  get 'org_path' => 'factorys#org'
  post 'org1_path' => 'factorys#org_rel'
  post 'phone' => 'factorys#phone'
  post 'mfg' => 'factorys#mfg_capacity' 

end

app/models/a_segment.rb
class ASegment < ActiveRecord::Base
	
end

app/models/classification.rb
require 'safe_attributes/base'
class AccountBase < ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("ksa_#{Rails.env}")
end
class Classification < AccountBase
end

app/models/ex_classification.rb
require 'safe_attributes/base'
class Accountex< ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("ex_#{Rails.env}")
end
class Ex_classification < Accountex
	include SafeAttributes::Base
	    self.table_name = 'classifications'
end

app/models/externalid.rb
require 'safe_attributes/base'
class Account < ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  end
class Externalid < Account
end

app/models/factory.rb
require 'safe_attributes/base'
class Account< ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
end
class Factory < Account
end

app/models/mfg_capacity.rb
class Account < ActiveRecord::Base
	 self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  
end
class Mfg_capacity < Account
end

app/models/nsnmrcxs.rb
class Nsnmrcxs < ActiveRecord::Base
	
	#has_one :NSN
		#searchkick text_start: [:NSN]
end

app/models/org_relationship.rb
class Account < ActiveRecord::Base
	# No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  
end
class Org_relationship < Account
end

app/models/organization.rb
require 'safe_attributes/base'
class Account < ActiveRecord::Base
	# No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  
end
class Organization < Account
end

app/models/phone.rb
class Account < ActiveRecord::Base
	# No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  
end
class Phone < Account
end

app/models/reference_datum.rb
class ReferenceDatum < ActiveRecord::Base
end

app/models/source_datum.rb
class SourceDatum < ActiveRecord::Base
end

app/models/term_dn.rb
require 'safe_attributes/base'
class AccountDic < ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("eotd_#{Rails.env}")
end
class Term_dn < AccountDic
	include SafeAttributes::Base
	    self.table_name = 'term_dn'
	
end

class Definition < AccountDic
	include SafeAttributes::Base
	    self.table_name = 'definition_dn'
end

class Concept_dn < AccountDic
	include SafeAttributes::Base
	    self.table_name = 'concept_dn'
end

app/models/user.rb
class User < ActiveRecord::Base
  #has_secure_password
 
end

app/controllers/factorys_controller.rb
require 'wice_grid'
class FactorysController < ApplicationController
	
	def show
    if(session[:user_id])
    @factory = initialize_grid(Factory,:per_page=>10)
    @factory1= Factory.where(:FPKID => params[:query])
    else
    render 'sessions/login'
    end
  end

  def view
    if(session[:user_id])
       var = request.query_parameters
      @data = var['FPKID']
       @viewfpkid =Factory.where("FPKID = ? ", @data )
    else
       render 'sessions/login'
    end
  end

  def external_view
     if(session[:user_id])
       var = request.query_parameters
      @data1 = var['Factory_ID']
       @view_extern =Externalid.where("Factory_ID = ? ", @data1 )
    else
       render 'sessions/login'
    end
    end

  def org
     if(session[:user_id])
      var = request.query_parameters
      @data2 = var['OrganizationID']
      @org =Organization.where("OrganizationID = ? ", @data2 )
     else
      render 'session/login'
     end
      end

  def org_rel
     if(session[:user_id])
      var = request.query_parameters
      @data3 = var['OrganizationID']
      @org1 =Org_relationship.where("Org_ID1 = ? ", @data3 )
     else
      render 'session/login'
     end    
    end

  def phone
     if(session[:user_id])
      var = request.query_parameters
      @phone = var['Factory_ID']
      @phone1 =Phone.where("Factory_ID = ? ", @phone )
     else
      render 'session/login'
     end    
    end

  def mfg_capacity
     if(session[:user_id])
      var = request.query_parameters
      @mfg = var['Factory_ID']
      @mfg1 =Mfg_capacity.where("Factory_ID = ? ", @mfg )
     else
      render 'session/login'
     end    
    end

  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def minor

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/source_data_helper.rb
module SourceDataHelper
end

app/helpers/sourcedata_helper.rb
module SourcedataHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/factorys/external_view.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <img alt="image" class="img-responsive" src="<%= image_url 'headerlogo.jpg' %> " height="50px" />
        <!--  <div class="col-lg-6">
        <img alt="image" src="<%= image_url 'l3.jpg' %>" style="margin-left:-15px;" />
        </div>
        <div class="col-lg-2">
        <img alt="image" src="<%= image_url 'l2.jpg' %>" style="align:center;"/>
        </div>
        <div class="col-lg-4">
            <img alt="image" src="<%= image_url 'l1.jpg' %>" style="margin-top:15px;margin-left:220px;" />
        </div>  -->
        
        <div class="clearfix"></div>
         <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'source_data', :action => 'chart' %>">Dashboard</a>
        </li>
        <li>
             <a href="<%= url_for :controller => 'factorys', :action => 'show' %>">Factory Searcher</a>
        </li>
        <li class="active">
            <strong>External View</strong>
        </li>
    </ol>
        
    </div>
</div>
        <div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
            <h2>External View</h2>
             <table class="table table-bordered" style="outline:thin solid">
                <tr>
                    <th colspan="2">FACTORY_ID :    <%= @data1  %></th>
                </tr>
            </table>
              <% @view_extern.each do |v| %> 
                <table class="table table-bordered" style="outline:thin solid">
                    <tr> 
                        <th>XID_DESCRIPTION</th>
                        <td><%= v.XID_Description %> </td>
                    </tr>
                    <tr> 
                        <th>SUBMITTING_AGENCY</th>
                        <td><%= v.Submitting_Agency %> </td>
                    </tr>                       
                </table>
                 <% end %>
               
             </div>
        </div>
     </div>      
</div>
</div>
<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    var updateOutput = function (e) {
        var list = e.length ? e : $(e.target),
                output = list.data('output');
        if (window.JSON) {
            output.val(window.JSON.stringify(list.nestable('serialize')));//, null, 2));
        } else {
            output.val('JSON browser support required for this demo.');
        }
    };
    // activate Nestable for list 1
    $('#nestable').nestable({
        group: 1
    }).on('change', updateOutput);

    // activate Nestable for list 2
    $('#nestable2').nestable({
        group: 1
    }).on('change', updateOutput);

    // output initial serialised data
    updateOutput($('#nestable').data('output', $('#nestable-output')));
    updateOutput($('#nestable2').data('output', $('#nestable2-output')));

    $('#nestable-menu').on('click', function (e) {
        var target = $(e.target),
                action = target.data('action');
        if (action === 'expand-all') {
            $('.dd').nestable('expandAll');
        }
        if (action === 'collapse-all') {
            $('.dd').nestable('collapseAll');
        }
    });

});

</script>

<% end %>
 

app/views/factorys/factorylist.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>FACTORY SEARCH</h2>
        <ol class="breadcrumb">
	        <li class="active">
	           
	        </li>
    	</ol>
    	
    </div>
    
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
    <% if notice %>
        <div class="col-lg-12">
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                <p id="notice"><%= notice %></p>
            </div>
        </div>
    <% end %>
    <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Factory Search List</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <!-- <li>
                                <a href="#">Config option 1</a>
                            </li>
                            <li>
                                <a href="#">Config option 2</a>
                            </li> -->
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                <div style="width:100%; overflow-x:auto;">
                <%= grid(@factory, :html => {:class => 'table table-striped table-bordered table-hover dataTables-example', :id => ''}) do |q|
                    # String
                end %>     
            </div>
            </div>
         </div>
    </div>
</div>
 </div>

app/views/factorys/mfg_capacity.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <img alt="image" class="img-responsive" src="<%= image_url 'headerlogo.jpg' %> " height="50px" />
        <!--  <div class="col-lg-6">
        <img alt="image" src="<%= image_url 'l3.jpg' %>" style="margin-left:-15px;" />
        </div>
        <div class="col-lg-2">
        <img alt="image" src="<%= image_url 'l2.jpg' %>" style="align:center;"/>
        </div>
        <div class="col-lg-4">
            <img alt="image" src="<%= image_url 'l1.jpg' %>" style="margin-top:15px;margin-left:220px;" />
        </div>  -->
        
        <div class="clearfix"></div>
         <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'source_data', :action => 'chart' %>">Dashboard</a>
        </li>
        <li>
             <a href="<%= url_for :controller => 'factorys', :action => 'show' %>">Factory Searcher</a>
        </li>
        <li class="active">
            <strong>Mfg Capacity View</strong>
        </li>
    </ol>
        
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
             <h2>MFG CAPACITY VIEW</h2>
             <table class="table table-bordered" style="outline:thin solid">
                <tr>
                    <th colspan="2">FACTORY_ID :   <%= @mfg %> </th>                    
                </tr>
            </table>
            <% @mfg1.each do |v| %> 
                <table class="table table-bordered" style="outline:thin solid">
                    
                        <tr> 
                            <th>PK_ID</th>
                            <td><%= v.PK_ID %> </td>
                        </tr>
                         <tr> 
                            <th>ISIC4_CODE</th>
                            <td><%= v.ISIC4_Code %> </td>
                        </tr>
                         <tr> 
                            <th>CAPACITY</th>
                            <td><%= v.Capacity %> </td>
                        </tr>
                         <tr> 
                            <th>UOM</th>
                            <td><%= v.UOM %> </td>
                        </tr>
                         <tr> 
                            <th>PERIOD_OF_MEASURE</th>
                            <td><%= v.Period_of_Measure %> </td>
                        </tr>
                         <tr> 
                            <th>LANGUAGE</th>
                            <td><%= v.Language %> </td>
                        </tr>
                        
                </table>
               <% end -%>
            </div>
        </div>
    </div>
</div>
</div>
 

app/views/factorys/org.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <img alt="image" class="img-responsive" src="<%= image_url 'headerlogo.jpg' %> " height="50px" />
        <!--  <div class="col-lg-6">
        <img alt="image" src="<%= image_url 'l3.jpg' %>" style="margin-left:-15px;" />
        </div>
        <div class="col-lg-2">
        <img alt="image" src="<%= image_url 'l2.jpg' %>" style="align:center;"/>
        </div>
        <div class="col-lg-4">
            <img alt="image" src="<%= image_url 'l1.jpg' %>" style="margin-top:15px;margin-left:220px;" />
        </div>  -->
        
        <div class="clearfix"></div>
         <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'source_data', :action => 'chart' %>">Dashboard</a>
        </li>
        <li>
             <a href="<%= url_for :controller => 'factorys', :action => 'show' %>">Factory Searcher</a>
        </li>
        <li class="active">
            <strong>Organisation</strong>
        </li>
    </ol>
        
    </div>
</div>

    <div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
            <h2>Organisation</h2>
                <table class="table table-bordered">
                     <% @org.each do |a| %> 
                        <tr> 
                            <th>ORGANIZATION_ID</th>
                            <td><%= a.OrganizationID %> </td>
                        </tr>
                        <tr> 
                            <th>ORGANIZATION_NAME</th>
                            <td><%= a.Organization_Name %> </td>
                        </tr>
                        <tr> 
                            <th>LAGAL_ENTITY_TYPE</th>
                            <td><%= a.Legal_Entity_Type %> </td>
                        </tr>
                        <tr> 
                            <th>TRADE_NAME</th>
                            <td><%= a.Trade_Name %> </td>
                        </tr>
                        <tr> 
                            <th>HOMEPAGE_URL</th>
                            <td><%= a.Homepage_URL %> </td>
                        </tr>
                        <tr> 
                            <th>EMAIL_ADDRESS</th>
                            <td><%= a.Email_Address %> </td>
                        </tr>
                        <tr> 
                            <th>LANGUAGE</th>
                            <td><%= a.Language %> </td>
                        </tr>

                </table>
                 <%= button_to "ORGANIZATION RELATIONSHIP" , {:controller => :factorys,:action => :org_rel,:OrganizationID => a.OrganizationID
                   } %>
            </div>
        </div>
    </div>
</div>
</div>
<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    var updateOutput = function (e) {
        var list = e.length ? e : $(e.target),
                output = list.data('output');
        if (window.JSON) {
            output.val(window.JSON.stringify(list.nestable('serialize')));//, null, 2));
        } else {
            output.val('JSON browser support required for this demo.');
        }
    };
    // activate Nestable for list 1
    $('#nestable').nestable({
        group: 1
    }).on('change', updateOutput);

    // activate Nestable for list 2
    $('#nestable2').nestable({
        group: 1
    }).on('change', updateOutput);

    // output initial serialised data
    updateOutput($('#nestable').data('output', $('#nestable-output')));
    updateOutput($('#nestable2').data('output', $('#nestable2-output')));

    $('#nestable-menu').on('click', function (e) {
        var target = $(e.target),
                action = target.data('action');
        if (action === 'expand-all') {
            $('.dd').nestable('expandAll');
        }
        if (action === 'collapse-all') {
            $('.dd').nestable('collapseAll');
        }
    });

});

</script>

<% end %>
 <% end %>
 

app/views/factorys/org_rel.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <img alt="image" class="img-responsive" src="<%= image_url 'headerlogo.jpg' %> " height="50px" />
        <!--  <div class="col-lg-6">
        <img alt="image" src="<%= image_url 'l3.jpg' %>" style="margin-left:-15px;" />
        </div>
        <div class="col-lg-2">
        <img alt="image" src="<%= image_url 'l2.jpg' %>" style="align:center;"/>
        </div>
        <div class="col-lg-4">
            <img alt="image" src="<%= image_url 'l1.jpg' %>" style="margin-top:15px;margin-left:220px;" />
        </div>  -->
        
        <div class="clearfix"></div>
         <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'source_data', :action => 'chart' %>">Dashboard</a>
        </li>
        <li>
             <a href="<%= url_for :controller => 'factorys', :action => 'show' %>">Factory Searcher</a>
        </li>
        <li class="active">
            <strong>Organisation Realtionship</strong>
        </li>
    </ol>
        
    </div>
</div>


    <div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
            <h2>Organisation Relationship</h2>
                <table class="table table-bordered">
                  <% @org1.each do |a| %> 
                  <tr> 
                            <th>RELATIONSHIP_ID</th>
                            <td><%= a.Relationship_ID %> </td>
                  </tr>
                  <tr> 
                            <th>ORG_ID1</th>
                            <td><%= a.Org_ID1 %> </td>
                  </tr>
                  <tr> 
                            <th>ORG_ID2</th>
                            <td><%= a.Org_ID2 %> </td>
                  </tr>
                  <tr> 
                            <th>LEGAL_ENTITY_TYPE</th>
                            <td><%= a.Legal_Entity_Type %> </td>
                  </tr>
                  <tr> 
                            <th>OWNERSHIP_RELATIONSHIP_TYPE</th>
                            <td><%= a.Ownership_Relationship_Type %> </td>
                  </tr>
                  <tr> 
                            <th>LANGUAGE</th>
                            <td><%= a.Language %> </td>
                  </tr>
                </table>
            </div>
        </div>
    </div>
</div>
</div>            
<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    var updateOutput = function (e) {
        var list = e.length ? e : $(e.target),
                output = list.data('output');
        if (window.JSON) {
            output.val(window.JSON.stringify(list.nestable('serialize')));//, null, 2));
        } else {
            output.val('JSON browser support required for this demo.');
        }
    };
    // activate Nestable for list 1
    $('#nestable').nestable({
        group: 1
    }).on('change', updateOutput);

    // activate Nestable for list 2
    $('#nestable2').nestable({
        group: 1
    }).on('change', updateOutput);

    // output initial serialised data
    updateOutput($('#nestable').data('output', $('#nestable-output')));
    updateOutput($('#nestable2').data('output', $('#nestable2-output')));

    $('#nestable-menu').on('click', function (e) {
        var target = $(e.target),
                action = target.data('action');
        if (action === 'expand-all') {
            $('.dd').nestable('expandAll');
        }
        if (action === 'collapse-all') {
            $('.dd').nestable('collapseAll');
        }
    });

});

</script>

<% end %>
 <% end %>
 

app/views/factorys/phone.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <img alt="image" class="img-responsive" src="<%= image_url 'headerlogo.jpg' %> " height="50px" />
        <!--  <div class="col-lg-6">
        <img alt="image" src="<%= image_url 'l3.jpg' %>" style="margin-left:-15px;" />
        </div>
        <div class="col-lg-2">
        <img alt="image" src="<%= image_url 'l2.jpg' %>" style="align:center;"/>
        </div>
        <div class="col-lg-4">
            <img alt="image" src="<%= image_url 'l1.jpg' %>" style="margin-top:15px;margin-left:220px;" />
        </div>  -->
        
        <div class="clearfix"></div>
         <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'source_data', :action => 'chart' %>">Dashboard</a>
        </li>
        <li>
             <a href="<%= url_for :controller => 'factorys', :action => 'show' %>">Factory Searcher</a>
        </li>
        <li class="active">
            <strong>Phone Information</strong>
        </li>
    </ol>
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
             <h2> Phone Information</h2>
                <table class="table table-bordered">
                     <% @phone1.each do |v| %> 
                        <tr> 
                            <th>PHONE_ID</th>
                            <td><%= v.Phone_ID %> </td>
                        </tr>
                        <tr> 
                            <th>FACTORY_ID</th>
                            <td><%= v.Factory_ID %> </td>
                        </tr>
                        <tr> 
                            <th>ORGANIZATION_ID</th>
                            <td><%= v.Organization_ID %> </td>
                        </tr>
                        <tr> 
                            <th>PHONE_NO</th>
                            <td><%= v.Phone_No %> </td>
                        </tr>
                        <tr> 
                            <th>TYPE</th>
                            <td><%= v.Type %> </td>
                        </tr>
                        <tr> 
                            <th>MOBILE</th>
                            <td><%= v.Mobile %> </td>
                        </tr>
                        <tr> 
                            <th>LANGUAGE</th>
                            <td><%= v.Language %> </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<% end -%>

app/views/factorys/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <img alt="image" class="img-responsive" src="<%= image_url 'headerlogo.jpg' %> " height="50px" />
        <!--  <div class="col-lg-6">
        <img alt="image" src="<%= image_url 'l3.jpg' %>" style="margin-left:-15px;" />
        </div>
        <div class="col-lg-2">
        <img alt="image" src="<%= image_url 'l2.jpg' %>" style="align:center;"/>
        </div>
        <div class="col-lg-4">
            <img alt="image" src="<%= image_url 'l1.jpg' %>" style="margin-top:15px;margin-left:220px;" />
        </div>  -->
        
        <div class="clearfix"></div>
         <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'source_data', :action => 'edit' %>">Dashboard</a>
        </li>
        <li class="active">
            <strong>FACTORY Searcher</strong>
        </li>
    </ol>
        
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
    <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Factory Search Results</h5>

                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <!-- <li>
                                <a href="#">Config option 1</a>
                            </li>
                            <li>
                                <a href="#">Config option 2</a>
                            </li>--> 
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                <div class="col-lg-6 pull-right">
                <%= form_tag(factorys_show_path, :method => "get", class: "navbar-form") do %>
                            <div class="form-group pull-right">
                             <%= text_field_tag :search, params[:search], class: "span4 form-control", placeholder: "Search" %>
                     
                      <%= submit_tag "Search", :class=>"btn btn btn-primary", :style=>"margin:0;",:name=>nil %> 
                    </div>
                  <% end %>
            </div>
            </br></br></br></br>
                <div style="width:100%; overflow-x:auto;">
                 <%= grid(@factory, :html => {:class => 'table table-striped table-bordered table-hover dataTables-example', :id => ''}) do |s|
				
		         	s.column :name => 'FPKID',:attribute => 'FPKID' 
		         		
                	s.column :name => 'Factory_ID', :attribute => 'Factory_ID' do  |s|
                		link_to s.Factory_ID ,{:controller => :factorys,:action => :external_view, :Factory_ID => s.Factory_ID},:target => "_blank"
		         	end
                	s.column :name => 'Factory_Name', :attribute => 'Factory_Name'
                	s.column :name => 'City', :attribute => 'City'
                	s.column  do  |s|
		         	link_to"" ,{:controller => :factorys,:action => :view, :FPKID =>  s.FPKID},:class=> "fa fa-external-link-square"
		         	 end
                end -%>
             
            	</div>
            	</div>
         </div>
    </div>
</div>
 </div>