config/routes.rb
Myapp::Application.routes.draw do
  resources :source_data
  root 'source_data#chart'
  get 'sessions/destroy'
  get 'nsnlist'=> 'source_data#nsnlist'
  get 'source'=> 'source_data#source'
  get 'edit' => 'source_data#edit'
  get 'viewsource' => 'source_data#viewsource'
  get 'view' => 'source_data#view'
  get 'dictionary_detail' => 'source_data#dictionary_detail'
  post   'login'   => 'sessions#create'
  get 'login' => 'sessions#login'
  get 'logout' => 'sessions#destroy'
  get 'new' => 'users#new'
  get 'factorys/show'
  get 'view_path' => 'factorys#view'
  get 'external_view_path' => 'factorys#external_view'
  get 'org_path' => 'factorys#org'
  post 'org1_path' => 'factorys#org_rel'
  post 'phone' => 'factorys#phone'
  post 'mfg' => 'factorys#mfg_capacity' 

end

app/models/a_segment.rb
class ASegment < ActiveRecord::Base
	
end

app/models/classification.rb
require 'safe_attributes/base'
class AccountBase < ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("ksa_#{Rails.env}")
end
class Classification < AccountBase
end

app/models/ex_classification.rb
require 'safe_attributes/base'
class Accountex< ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("ex_#{Rails.env}")
end
class Ex_classification < Accountex
	include SafeAttributes::Base
	    self.table_name = 'classifications'
end

app/models/externalid.rb
require 'safe_attributes/base'
class Account < ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  end
class Externalid < Account
end

app/models/factory.rb
require 'safe_attributes/base'
class Account< ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
end
class Factory < Account
end

app/models/mfg_capacity.rb
class Account < ActiveRecord::Base
	 self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  
end
class Mfg_capacity < Account
end

app/models/nsnmrcxs.rb
class Nsnmrcxs < ActiveRecord::Base
	
	#has_one :NSN
		#searchkick text_start: [:NSN]
end

app/models/org_relationship.rb
class Account < ActiveRecord::Base
	# No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  
end
class Org_relationship < Account
end

app/models/organization.rb
require 'safe_attributes/base'
class Account < ActiveRecord::Base
	# No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  
end
class Organization < Account
end

app/models/phone.rb
class Account < ActiveRecord::Base
	# No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("factory_#{Rails.env}")
  
end
class Phone < Account
end

app/models/reference_datum.rb
class ReferenceDatum < ActiveRecord::Base
end

app/models/source_datum.rb
class SourceDatum < ActiveRecord::Base
end

app/models/term_dn.rb
require 'safe_attributes/base'
class AccountDic < ActiveRecord::Base
  # No corresponding table in the DB.
  self.abstract_class = true

  # Open a connection to the appropriate database depending
  # on what RAILS_ENV is set to.
  establish_connection("eotd_#{Rails.env}")
end
class Term_dn < AccountDic
	include SafeAttributes::Base
	    self.table_name = 'term_dn'
	
end

class Definition < AccountDic
	include SafeAttributes::Base
	    self.table_name = 'definition_dn'
end

class Concept_dn < AccountDic
	include SafeAttributes::Base
	    self.table_name = 'concept_dn'
end

app/models/user.rb
class User < ActiveRecord::Base
  #has_secure_password
 
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/source_data_helper.rb
module SourceDataHelper
end

app/helpers/sourcedata_helper.rb
module SourcedataHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
        <strong>Email me:</strong>
    	<%= mail_to "info@eccma.org" do %>
	  	 	<span>info@eccma.org</span>
		<% end %>
    </div>
    <div>
        <strong>Copyright</strong> <%= link_to "Eccma", "http://www.eccma.org/", target: '_blank' %> &copy; <%= Time.now.year %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
             <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="image" class="img-circle" src="<%= image_url 'profile_small.jpg' %>"/>
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Sharon Koshy</strong>
                            </span> <span class="text-muted text-xs block">ECCMA CEO INDIA <!--b class="caret"></b--></span>
                        </span>
                    </a>
                    <!--ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="">Profile</a>
                        </li>
                        <li><a href="">Contacts</a>
                        </li>
                        <li><a href="">Mailbox</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="">Logout</a>
                        </li>
                    </ul-->
                </div>
                <div class="logo-element">
                    MCI
                </div>
            </li>
            <li class="<%= 'active' if current_page?('/') %>">
                <%= link_to "/" do %>
                <i class="fa fa-dashboard"></i> <span class="nav-label">Dashboard</span>
                <% end %>
            </li>
             <!-- <li class="<%= 'active' if current_page?('/') %>">
                <%= link_to "/" do %>
                <i class="fa fa-dashboard"></i> <span class="nav-label">Dashboard</span>
                <% end %>
            </li>
            <li class="<%= 'active' if current_page?('/cmms/dbmap') %>">
                <%= link_to "/cmms/dbmap" do %>
                <i class="fa fa-book"></i> <span class="nav-label">Databse Table</span>
                <% end %>
            </li>
             <li class="<%= 'active' if current_page?('/cmms/dbmap') %>">
                <%= link_to "/users/new" do %>
                <i class="fa fa-user"></i> <span class="nav-label">Create user</span>
                <% end %>
            </li>
            <li class="<%= 'active' if current_page?('/home/minor') %>">
                <%= link_to "/home/minor" do %>
                <i class="fa fa-desktop"></i> <span class="nav-label">Minor page</span>
                <% end %>
            </li> -->
        </ul>
    </div>
</nav>

app/views/layouts/_topnavbar.html.erb
<div class="row border-bottom">
    <!--nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0"-->
    <nav class="navbar navbar-fixed-top" role="navigation">   
       <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <!--form role="search" class="navbar-form-custom" method="post" action="/">
                <div class="form-group">
                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search" />
                </div>
            </form-->
        </div>
        <ul class="nav navbar-top-links navbar-right">
             <li>
                <span style="color:white;">Welcome to Ministry of Commerce and Industry</span>
            </li>
            
            <li>
                  <%= link_to 'Logout', sessions_destroy_path %>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KSA</title>
    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

</head>
<body class="md-skin fixed-nav">

    <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        <%= render 'layouts/navigation' %>

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            <%= render 'layouts/topnavbar' %>

            <!-- Main view  -->
            <%= yield %>

            <!-- Footer -->
            <%= render 'layouts/footer' %>

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->
     <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <!-- Include javascript per-view -->
    <!-- For demo purpose we include javascript in view but you can easily start SeedProject and organize it with Rails asset pipeline as you want -->
    <%= yield :javascript %>

</body>
</html>