config/routes.rb
Myapp::Application.routes.draw do
  resources :source_data
  root 'source_data#chart'
  get 'sessions/destroy'
  get 'nsnlist'=> 'source_data#nsnlist'
  get 'source'=> 'source_data#source'
  get 'edit' => 'source_data#edit'
  get 'viewsource' => 'source_data#viewsource'
  get 'view' => 'source_data#view'
  get 'dictionary_detail' => 'source_data#dictionary_detail'
  post   'login'   => 'sessions#create'
  get 'login' => 'sessions#login'
  get 'logout' => 'sessions#destroy'
  get 'new' => 'users#new'
  get 'factorys/show'
  get 'view_path' => 'factorys#view'
  get 'external_view_path' => 'factorys#external_view'
  get 'org_path' => 'factorys#org'
  post 'org1_path' => 'factorys#org_rel'
  post 'phone' => 'factorys#phone'
  post 'mfg' => 'factorys#mfg_capacity' 

end

app/controllers/source_data_controller.rb
class SourceDataController < ApplicationController
 
  def chart
    if session[:user_id]
      @db_cmm = SourceDatum.count(:id)
      @db_cmm_count=@db_cmm.to_s.size
      #db_cmm_first=@db_cmm.to_s.first(1).to_i
      # @ds= db_cmm_first.to_s.ljust(@db_cmm_count.to_i,'0')
      # @ds_cmm= @ds.to_i * 2
      @db_inv = SourceDatum.where(["FLAG= ?", 'INV']).count
      @db_locinv = SourceDatum.where(["FLAG= ?", 'LINV']).count
      @db_match = SourceDatum.where(["FLAG= ?", 'USV']).count
      @db_nonoff = SourceDatum.where(["FLAG= ?", 'USNV']).count
      @db_other = SourceDatum.where(["FLAG = ?", '']).count
      @db_matchgmv = SourceDatum.where(["FLAG= ?", 'GMV']).count
      @db_matchfrv = SourceDatum.where(["FLAG= ?", 'FRV']).count
      @db_matchukv = SourceDatum.where(["FLAG= ?", 'UKV']).count
      @db_nonoffgmv = SourceDatum.where(["FLAG= ?", 'GMNV']).count
      @db_nonoffrnv = SourceDatum.where(["FLAG= ?", 'FRNV']).count
      @db_nonoffuk = SourceDatum.where(["FLAG= ?", 'UKNV']).count


     #@db_inv_count=@db_inv.to_s.size

      # @db_classification = Classification.count(:cat_id)
      # @db_classification_count=@db_classification.to_s.size
      # db_classification_first=@db_classification.to_s.first(1).to_i
      # @ds= db_classification_first.to_s.ljust(@db_classification_count.to_i,'0')
      # @ds_classification= @ds.to_i * 2
      @db_classification = Classification.count(:cat_id)
      @db_classtotal =250000
      @db_classbalance = @db_classtotal-@db_classification

      # @db_factory = Factory.count(:FPKID)
      # @db_factory_count=@db_factory.to_s.size
      # db_factory_first=@db_factory.to_s.first(1).to_i
      # @ds= db_factory_first.to_s.ljust(@db_factory_count.to_i,'0')
      # @ds_factory= @ds.to_i * 2

      @db_factory = Factory.count(:id)
      @db_facttotal = 7000
      @db_factbalance = @db_facttotal-@db_factory
      # @db_factory_count=@db_factory.to_s.size
      # db_factory_first=@db_factory.to_s.first(1).to_i
      # @ds= db_factory_first.to_s.ljust(@db_factory_count.to_i,'0')
      # @ds_factory= @ds.to_i * 2

      @db_exclass = Ex_classification.count(:cat_id)
      @db_extotal = 1000000
      @db_exbalance = @db_extotal-@db_exclass
      # @db_exclass_count=@db_exclass.to_s.size
      # db_exclass_first=@db_exclass.to_s.first(1).to_i
      # @ds= db_exclass_first.to_s.ljust(@db_exclass_count.to_i,'0')
      # @ds_exclass= @ds.to_i * 2
       else
        render 'sessions/login'
      end
    end


  def nsnlist
    if session[:user_id]
      if params[:search]
        @vs = params[:search]
        #search= 19207
         @cmm = initialize_grid(ReferenceDatum ,conditions: ["CAGE_CD_9250 = ? OR NSN = ? OR REF_NBR_3570 = ? OR NAME = ?  ", @vs,@vs,@vs,@vs] , :per_page => 10)  

        else
         @cmm = initialize_grid(ReferenceDatum , :per_page => 10)  
      end
      else
        render 'sessions/login'
    end
  end

  def source
   vars = request.query_parameters
    @type = vars['TYPE']
      if session[:user_id]
          #all values in source data
          if @type =='all'
            if params[:search]
              @vs = params[:search]
              #search= 19207
               @cmm = initialize_grid(SourceDatum ,conditions: ["CAGEC = ? OR NSN = ? OR PART_NUMBER = ? OR NAME = ? ", @vs,@vs,@vs,@vs] , :per_page => 10)

              else
                @cmm = initialize_grid(SourceDatum , :per_page => 10)     
            end
         else
            if params[:search]
              @vs = params[:search]
            #search= 19207
              @cmm = initialize_grid(SourceDatum ,conditions: ["CAGEC = ? OR NSN = ? OR PART_NUMBER = ? OR NAME = ? ",@vs,@vs,@vs,@vs] , :per_page => 10)

            else
              @cmm = initialize_grid(SourceDatum , conditions: ["FLAG = ? ", @type] , :per_page => 10)   
            end
        end
      else
          render 'sessions/login'
      end
  end


   def edit
     if session[:user_id]
      vars = request.query_parameters
      @vid = vars['NSN']
          @count_NSN = ASegment.where(["NSN= ?", @vid])
          if @count_NSN.count == 1  
             @a_seg = ASegment.where(["NSN= ?", @vid])
          else
           
            respond_to do |format|
            format.html { redirect_to root_url, notice: 'This material is not found in A_segments' }
          end
        end
        @nsnmrcxs =Nsnmrcxs.where(["NSN= ?", @vid]) 
        @c_seg =ReferenceDatum.where(["NSN= ?", @vid]) 
        else
        render 'sessions/login'
      end
    end
    
    def viewsource
      if session[:user_id]
        vars = request.query_parameters
        @nsn = vars['NSN']
         @viewnsn =SourceDatum.where("NSN = ? ", @nsn )
      else
        render 'sessions/login'
      end
   end 

    def view
      if session[:user_id]
        vars = request.query_parameters
        @nsn = vars['NSN']
         @viewnsn =ReferenceDatum.where("NSN = ? ", @nsn )
          else
          render 'sessions/login'
        end
    end

    def dictionary_detail
       if session[:user_id]
        vars = request.query_parameters
        @esci = vars['esci']
        @term = vars['term']
        @definition = vars['def']
        #@mm = User.where("id = ?", 4).select( "user_fname, user_lname")
         @mm =Term_dn.where("term_ID = ? ", @term )
         @def =Definition.where("definition_ID = ? ", @definition )
          @con_dn =Concept_dn.where("concept_ID = ? AND term_ID = ? ", @esci, @term)
          else
          render 'sessions/login'
        end
    end



end

app/helpers/source_data_helper.rb
module SourceDataHelper
end

app/helpers/sourcedata_helper.rb
module SourcedataHelper
end

app/views/source_data/chart.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
        <img alt="image" class="img-responsive" src="<%= image_url 'headerlogo.jpg' %> " height="50px" />
        <!--  <div class="col-lg-6">
        <img alt="image" src="<%= image_url 'l3.jpg' %>" style="margin-left:-15px;" />
        </div>
        <div class="col-lg-2">
        <img alt="image" src="<%= image_url 'l2.jpg' %>" style="align:center;"/>
        </div>
        <div class="col-lg-4">
            <img alt="image" src="<%= image_url 'l1.jpg' %>" style="margin-top:15px;margin-left:220px;" />
        </div>  -->
        
        <div class="clearfix"></div>
        <ol class="breadcrumb">
            <li class="active">
                <a href="<%= url_for :controller => 'source_data', :action => 'chart' %>"><strong>Dashboard</strong></a>
            </li>
        </ol>
        
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
     <div class="col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>FACTORY Database</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>                    
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content text-center h-200">
                <span id="db_factory"></span>
                <div class="row" style="padding-top:10px;">
                    <div class="col-md-6">
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#3366CC;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'factorys', :action => 'show'%>" target="_blank">&nbsp;&nbsp; Total(<%= @db_facttotal.inspect %>)</a></div>
                    </div>  
                    <div class="col-md-6">
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#DC3912;"></div>
                         <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'factorys', :action => 'show'%>" target="_blank">&nbsp;&nbsp;No.of Factories(<%= @db_factory.inspect %>)</a></div>
                    </div>                    
                </div>              
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>MADE IN KSA Database</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>                    
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content text-center h-200">
                <span id="db_ksa"></span>
                <div class="row" style="padding-top:10px;">
                    <div class="col-md-6">
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#3366CC;"></div>
                        <div class="pull-left"> &nbsp;&nbsp;Total (<%= @db_classtotal.inspect %>)</div>
                    </div>  
                    <div class="col-md-6">
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#DC3912;"></div>
                        <div class="pull-left"> &nbsp;&nbsp;No.of Items (<%= @db_classification.inspect %>)</div>
                    </div>                    
                </div>       
            </div>
        </div>
    </div> 
    <div class="col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5> CMM Database</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>                    
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content text-center h-200">
                <span id="db_cmm"></span>
                <div class="row" style="padding-top:10px;">
                    <div class="col-md-6">
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#ffff;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source' ,:TYPE => 'all' %>" target="_blank">&nbsp;&nbsp;Total NSN(<%= @db_cmm.inspect  %>)</a></div><br>
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#00FFFF;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => 'INV' %>" target="_blank">&nbsp;&nbsp;Invalid NSN(<%= @db_inv.inspect %>)</a></div><br>
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#3366CC;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => 'LINV' %>" target="_blank">&nbsp;&nbsp;Local NSN(<%= @db_locinv.inspect %>)</a></div><br>
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#DC3912;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'nsnlist' %>" target="_blank">&nbsp;&nbsp;Official NSN - USA(<%= @db_match.inspect %>)</a></div><br>
                         <div class="pull-left" style="width:15px;height:15px;;background-color:#FF1493;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => 'USNV' %>" target="_blank">&nbsp;&nbsp;Non-Official NSN - USA(<%= @db_nonoff.inspect %>)</a></div><br>
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#66AA01;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => 'GMV' %>" target="_blank">&nbsp;&nbsp;Official NSN - DEU(<%= @db_matchgmv.inspect %>)</a></div><br>
                        <!-- <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'nsnlist' %>" target="_blank">-Other Countries (<%= @db_other.inspect %>)</a></div><br>
 -->
                    </div>  
                    <div class="col-md-6">
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#FF7F50;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => 'FRV' %>" target="_blank">&nbsp;&nbsp;Official NSN - FRA(<%= @db_matchfrv.inspect %>)</a></div><br>
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#0199C6;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => 'UKV' %>" target="_blank">&nbsp;&nbsp;Official NSN - GBR(<%= @db_matchukv.inspect %>)</a></div><br>
                         <div class="pull-left" style="width:15px;height:15px;;background-color:#990199;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => 'GMNV' %>" target="_blank">&nbsp;&nbsp;Non-Official NSN - DEU(<%= @db_nonoffgmv.inspect %>)</a></div><br>
                        
                         <div class="pull-left" style="width:15px;height:15px;;background-color:#DB7093;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => 'FRNV' %>" target="_blank">&nbsp;&nbsp;Non-Official NSN - FRA(<%= @db_nonoffrnv.inspect %>)</a></div><br>
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#DEB887;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => 'UKNV' %>" target="_blank">&nbsp;&nbsp;Non-Official NSN - GBR(<%= @db_nonoffuk.inspect %>)</a></div><br>
                         <div class="pull-left" style="width:15px;height:15px;;background-color:#8B4513;"></div>
                        <div class="pull-left"> &nbsp;<a href="<%= url_for :controller => 'source_data', :action => 'source',:TYPE => '' %>" target="_blank">&nbsp;&nbsp;Other Countries NSN(<%= @db_other.inspect %>)</a></div>
                        
                    </div>                    
                </div>    
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>EXCEPTION Database</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>                    
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content text-center h-200">
                <span id="db_excemption"></span>
                <div class="row" style="padding-top:10px;">
                    <div class="col-md-6">
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#3366CC;"></div>
                        <div class="pull-left"> &nbsp;&nbsp;Total(<%= @db_extotal.inspect %>)</div>
                    </div>  
                    <div class="col-md-6 ">
                        <div class="pull-left" style="width:15px;height:15px;;background-color:#DC3912;"></div>
                        <div class="pull-left"> &nbsp;&nbsp;No.of Items(<%= @db_exclass.inspect %>)</div>
                    </div>                    
                </div>   
            </div>
        </div>
    </div> 
</div>
</div>


<% content_for :javascript do %>

<script type="text/javascript">


$(function() {
    $("#db_cmm").sparkline(['<%= @db_inv.inspect %>','<%= @db_locinv.inspect %>','<%= @db_match.inspect %>','<%= @db_nonoff.inspect %>','<%= @db_matchgmv.inspect %>','<%= @db_matchfrv.inspect %>','<%= @db_matchukv.inspect %>','<%= @db_nonoffgmv.inspect %>','<%= @db_nonoffrnv.inspect %>','<%= @db_nonoffuk.inspect %>','<%= @db_other.inspect %>'], {
        type: 'pie',
        height: '250px',
        sliceColors: ['#00FFFF','#3366cc','#dc3912','#FF1493','#66aa00','#FF7F50','#0099c6','#990099','#DB7093','#DEB887','#8B4513'],
        //sliceColors: ['#1ab394','#B5B8CF'],
        highlight: "#1ab394",
        scaleBackdropColor: "rgba(255,255,255,0.75)",
    });  
    
    $("#db_factory").sparkline(['<%= @db_factbalance.inspect %>', '<%= @db_factory.inspect %>'], {
        type: 'pie',
         height: '250px',
         sliceColors: ['#3366cc','#dc3912','#ff9900','#109618','#66aa00','#dd4477','#0099c6','#990099','#B0C4DE'],
        //sliceColors: ['#1ab394','#B5B8CF'],
       highlight: "#1ab394",
        scaleBackdropColor: "rgba(255,255,255,0.75)",

     });

    $("#db_ksa").sparkline(['<%= @db_classbalance.inspect %>', '<%= @db_classification.inspect %>'], {
       type: 'pie',
       height: '250px',
        sliceColors: ['#3366cc','#dc3912','#ff9900','#109618','#66aa00','#dd4477','#0099c6','#990099'],
    //     //sliceColors: ['#1ab394','#B5B8CF'],
         highlight: "#1ab394",
         scaleBackdropColor: "rgba(255,255,255,0.75)",
     }); 

     $("#db_excemption").sparkline(['<%= @db_exbalance.inspect %>', '<%= @db_exclass.inspect %>'], {
        type: 'pie',
       height: '250px',
       sliceColors: ['#3366cc','#dc3912','#ff9900','#109618','#66aa00','#dd4477','#0099c6','#990099'],
    //     //sliceColors: ['#1ab394','#B5B8CF'],
        highlight: "#1ab394",
        scaleBackdropColor: "rgba(255,255,255,0.75)",
    });   
});

</script>

<% end %>

app/views/source_data/nsnlist.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
    	<img alt="image" class="img-responsive" src="<%= image_url 'headerlogo.jpg' %> " height="50px" />
    	<!--  <div class="col-lg-6">
        <img alt="image" src="<%= image_url 'l3.jpg' %>" style="margin-left:-15px;" />
        </div>
        <div class="col-lg-2">
    	<img alt="image" src="<%= image_url 'l2.jpg' %>" style="align:center;"/>
        </div>
    	<div class="col-lg-4">
    		<img alt="image" src="<%= image_url 'l1.jpg' %>" style="margin-top:15px;margin-left:220px;" />
    	</div>  -->
    	
        <div class="clearfix"></div>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'source_data', :action => 'nsnlist' %>">Dashboard</a>
        	</li>
	        <li class="active">
	            <strong>CMM Searcher</strong>
	        </li>
    	</ol>
    	
	</div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
				    <h5>CMM Search Results</h5>
				    <div class="ibox-tools">
				        <a class="collapse-link">
				            <i class="fa fa-chevron-up"></i>
				        </a>
				        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
				       		<i class="fa fa-wrench"></i>
				        </a>
				        <ul class="dropdown-menu dropdown-user">
				            <!-- <li>
				                <a href="#">Config option 1</a>
				            </li>
				            <li>
				                <a href="#">Config option 2</a>
				            </li> -->
				        </ul>
				        <a class="close-link">
				            <i class="fa fa-times"></i>
				        </a>
				    </div>
				</div>
			<div class="ibox-content">
			<div class="col-lg-6 pull-right">
				<%= form_tag(nsnlist_path, :method => "get", class: "navbar-form") do %>
				    		<div class="form-group pull-right">
				     		 <%= text_field_tag :search, params[:search], class: "span4 form-control", placeholder: "Search" %>
				     
				      <%= submit_tag "Search", :class=>"btn btn btn-primary", :style=>"margin:0;",:name=>nil %>	
				    </div>
				  <% end %>
			</div>
			</br></br></br></br>
			<div style="width:100%; overflow-x:auto;">
				<%= grid(@cmm, :html => {:class => 'table table-striped table-bordered table-hover dataTables-example', :id => ''}) do |g|
					# String
						
                	g.column :name => 'NSN', :attribute => 'NSN' do  |g|
		         	 link_to g.NSN,{:controller => :source_data,:action => :edit, :NSN => g.NSN} ,:target => "_blank" 
		         	end
  					g.column :name => 'CAGE CODE', :attribute => 'CAGE_CD_9250'
  					g.column :name => 'PART NUMBER', :attribute => 'REF_NBR_3570'
  					
  					g.column :name => 'NAME', :attribute => 'NAME'
  					
					g.column  do  |g|

		         	 link_to"" ,{ :controller => :source_data,:action => :view, :update => g.NSN, :NSN => g.NSN} ,:target => "_blank" ,:class=> "fa fa-external-link-square", title: 'View more data', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom'
		         	 end
		         	 g.column  do  |g|

		         	link_to"" ,{:controller => :source_data,:action => :viewsource, :NSN =>  g.NSN },:target => "_blank" ,:class=> "fa fa-eye", title: 'View source data', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom'
		         	 end

			end %>		
			</div>
			</div>
		</div>
	</div>
</div>
</div>

app/views/source_data/source.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-12">
    	<img alt="image" class="img-responsive" src="<%= image_url 'headerlogo.jpg' %> " height="50px" />
    	<!--  <div class="col-lg-6">
        <img alt="image" src="<%= image_url 'l3.jpg' %>" style="margin-left:-15px;" />
        </div>
        <div class="col-lg-2">
    	<img alt="image" src="<%= image_url 'l2.jpg' %>" style="align:center;"/>
        </div>
    	<div class="col-lg-4">
    		<img alt="image" src="<%= image_url 'l1.jpg' %>" style="margin-top:15px;margin-left:220px;" />
    	</div>  -->
    	
        <div class="clearfix"></div>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'source_data', :action => 'nsnlist' %>">Dashboard</a>
        	</li>
	        <li class="active">
	            <strong>CMM Searcher</strong>
	        </li>
    	</ol>
    	
	</div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
				<% if @type=="all"%>
				    <h5>CMM Search Results</h5>
				 <% else %>
				 	<% if @type =="INV" %>
				 		<h5>INVALID NSN Search Results</h5>
				 	<% end %>
				 	<% if @type =="LINV" %>
				 		<h5>LOCAL NSN Search Results</h5>
				 	<% end %>
				 	<% if @type =="FRV" %>
				 		<h5>OFFICIAL NSN - FRA Search Results</h5>
				 	<% end %>
				 	<% if @type =="FRNV" %>
				 		<h5>NON-OFFICIAL NSN - FRA Search Results</h5>
				 	<% end %>
				 	<% if @type =="GMV" %>
				 		<h5>OFFICIAL NSN - DEU Search Results</h5>
				 	<% end %>
				 	<% if @type =="GMNV" %>
				 		<h5>NON-OFFICIAL NSN - DEU Search Results</h5>
				 	<% end %>
				 	<% if @type =="UKV" %>
				 		<h5>OFFICIAL NSN - GBR Search Results</h5>
				 	<% end %>
				 	<% if @type =="UKNV" %>
				 		<h5>NON-OFFICIAL NSN - GBR Search Results</h5>
				 	<% end %>
				 	<% if @type =="" %>
				 		<h5>OTHER COUNTRY NSN Search Results</h5>
				 	<% end %>
				 <% end %>
				    <div class="ibox-tools">
				        <a class="collapse-link">
				            <i class="fa fa-chevron-up"></i>
				        </a>
				        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
				       		<i class="fa fa-wrench"></i>
				        </a>
				        <ul class="dropdown-menu dropdown-user">
				            <!-- <li>
				                <a href="#">Config option 1</a>
				            </li>
				            <li>
				                <a href="#">Config option 2</a>
				            </li> -->
				        </ul>
				        <a class="close-link">
				            <i class="fa fa-times"></i>
				        </a>
				    </div>
				</div>
			<div class="ibox-content">
			<div class="col-lg-6 pull-right">
				<%= form_tag(source_path, :method => "get", class: "navbar-form") do %>
				    		<div class="form-group pull-right">
				     		 <%= text_field_tag :search, params[:search], class: "span4 form-control", placeholder: "Search" %>
				     		<input type="text" class="hide" name="TYPE" value="<%= @type %>">
				     
				      <%= submit_tag "Search", :class=>"btn btn btn-primary", :style=>"margin:0;",:name=>nil %>	
				    </div>
				  <% end %>
			</div>
			</br></br></br></br>
			<div style="width:100%; overflow-x:auto;">
				<%= grid(@cmm, :html => {:class => 'table table-striped table-bordered table-hover dataTables-example', :id => ''}) do |g|
					# String
						
                	g.column :name => 'NSN', :attribute => 'NSN' 
  					g.column :name => 'CAGE CODE', :attribute => 'CAGEC'
  					g.column :name => 'PART NUMBER', :attribute => 'PART_NUMBER'
  					
  					g.column :name => 'NAME', :attribute => 'NAME'
					
		         	 g.column  do  |g|

		         	link_to"" ,{:controller => :source_data,:action => :viewsource, :NSN =>  g.NSN },:target => "_blank" ,:class=> "fa fa-eye", title: 'View source data', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom'
		         	 end

			end %>		
			</div>
			</div>
		</div>
	</div>
</div>
</div>